### ISSUE TITLE
[Feature Request]: provide a way to set options or parameters

### ISSUE THREAD

**Issue by pabloglombovsky** [rikyoz/bit7z#103]
### Feature description

I need to avoid storing the NTFS extra field (where the last accessed, modified, and created times are stored). I saw that one way to do it in 7zip was to use the -mtc=off parameter.
I did not find any way to do it when creating a .zip file using this library. Is there any way?
Thanks

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> I did not find any way to do it when creating a .zip file using this library. Is there any way?

Unfortunately, no, it's not possible with the library's current versions (stable and beta).
However, I'll probably add this option to the library's next version.
The change should not take much effort in itself, but I'm thinking of providing a more general way to set custom 7-zip parameters.

**Comment by pabloglombovsky** [comment]
Hi Riccardo,
One question about the 7zip wrapper.
In 7 zip there is no way to encrypt a file (using the .zip format) using a
password that contains Asian characters or even accentuated characters (any
character beyond the ASCII 127).
Do you know if there is a way using your library to bypass this?
Thanks

**Comment by rikyoz** [comment]
Hi!
> Do you know if there is a way using your library to bypass this?

Unfortunately, I don't think there's any way to bypass this limitation unless you directly modify the 7-zip source code.
I did some quick tests, and bit7z fails when using Asian/accentuated characters for `.zip` passwords: this is due to the internal calls to 7-zip failing, so I don't think there's much that bit7z can do in this case, I'm sorry!

**Comment by rikyoz** [comment]
Implemented in [v4.0.0](https://github.com/rikyoz/bit7z/releases/tag/v4.0.0).
