### ISSUE TITLE
[Feature Request]: Getting CRC32 information from files

### ISSUE THREAD

**Issue by RScherzer** [rikyoz/bit7z#104]
### Feature description

Maybe I did oversee it but is there no getter to receive the crc32 hash information from the stored files in the archive? Name is there in BitArchiveItem and others...but no crc32? Would be great if you can make it available (at least for zip/7z/rar).

...update...I mean without recalculating the crc32 hash value on the data, just a getter for the crc32 values (if available) stored in the archived files structures

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> Maybe I did oversee it but is there no getter to receive the crc32 hash information from the stored files in the archive?

There's no _direct_ getter for the crc32 checksum.
However, you can get the CRC32 hash of an archive's item as follows:

```cpp
uint32_t crc32 = 0;
auto crc_property = item.getProperty( BitProperty::CRC ); // BitPropVariant object
if ( crc_property.isUInt32() ) { // Just to be sure that the variant value has the correct type.
    crc32 = crc_property.getUInt32();
}
```

As far as I know, CRC32 variant values returned by 7-zip are either of `UInt32` or `Empty` type, so you might need to check only if `!crc_property.isEmpty()`.

> Would be great if you can make it available (at least for zip/7z/rar).

I will definitely add a getter to the item's class in a future version of the library!

> ...update...I mean without recalculating the crc32 hash value on the data, just a getter for the crc32 values (if available) stored in the archived files structures

As far as I know, the CRC property provided by 7-zip is the one stored in the archive file structures.

Hope that helps!

**Comment by RScherzer** [comment]
works perfectly fine, thanks

**Comment by rikyoz** [comment]
No problem! :D
