### ISSUE TITLE
[Bug]: Why can't compress an empty directory?

### ISSUE THREAD

**Issue by kak13amaplus** [rikyoz/bit7z#114]
### bit7z version

4.0.x beta

### 7-zip version

v21.07

### 7-zip DLL used

7z.dll

### MSVC version

2019

### Architecture

x86_64

### Which version of Windows are you using?

Windows 10

### Bug description

Why can't compress an empty directory?

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Which `BitFileCompressor`'s function are you using?
Could you provide any piece of the code?
Thank you!

**Comment by kak13amaplus** [comment]
#include "bitcompressor.hpp"

using namespace bit7z;

try {
    Bit7zLibrary lib{ L"7z.dll" };
    BitCompressor compressor{ lib, BitFormat::Zip };

   //The first parameter is dir
    compressor.compressFiles( Dir, L"protected_archive.zip" );

    } catch ( const BitException& ex ) {
    //do something with ex.what()...
}

**Comment by rikyoz** [comment]
> #include "bitcompressor.hpp"
> 
> using namespace bit7z;
> 
> try {
> Bit7zLibrary lib{ L"7z.dll" }; 
> BitCompressor compressor{ lib, BitFormat::Zip };
> 
> //The first parameter is dir 
> compressor.compressFiles( Dir, L"protected_archive.zip" );
> 
> ```
> } catch ( const BitException& ex ) {
> //do something with ex.what()...
> ```
> 
> }

> If an empty folder in Dir, the empty folder will not be compressed

This is the expected default behavior of `compressFiles`.
This function is meant to be used when you want to compress _only_ the files inside the `Dir` path; hence, empty folders will be ignored by default.


> I modified part of the code, 
> compressFiles‘s param filter L"* . *" -> L""
> FSIndexer::listDirectoryItems
> if ( item_matches ) -> if ( item_matches || current_item.isDir )
> 
> so that the empty folder can be compressed

I think that the changes to `FSIndexer::listDirectoryItems` are unnecessary.

Calling `compressFiles` with `L"*"` as the `filter` parameter should suffice, e.g., `compressor.compressFiles( Dir, L"protected_archive.zip", true, L"*" )`.
