### ISSUE TITLE
[Bug]:Rar file decompression progress is not accurate

### ISSUE THREAD

**Issue by liugantang** [rikyoz/bit7z#115]
### bit7z version

4.0.x beta, 3.1.x

### 7-zip version

v21.06

### 7-zip DLL used

7z.dll

### MSVC version

2019

### Architecture

x86

### Which version of Windows are you using?

Windows 10

### Bug description

I found that the progress output when the rar file is decompressed is not accurate. The actual file size is always larger than the output progress.
Here is my code：
```
bool progress(uint64_t val)
{
	std::cout << val << std::endl;
	return true;
}

int main()
{
	std::wstring srcPath = L"C:\\Users\\Administrator\\Downloads\\test.rar";
	std::wstring dstPath = L"C:\\Users\\Administrator\\Downloads\\test";
	try {
		Bit7zLibrary lib;
		BitArchiveReader reader{ lib, srcPath,BitFormat::Rar5 };
		uint64_t fSize = reader.size();
		uint64_t pSize = reader.packSize();
		std::cout << "file size:" << fSize<<std::endl;
		std::cout << "pack size:" << pSize << std::endl;
		BitFileExtractor extractor(lib, BitFormat::Rar5);
		extractor.setProgressCallback(progress);
		
		extractor.extract(srcPath, dstPath);

	}
	catch (BitException& ex) {
		std::wcout << ex.what() << std::endl;
	}
	return 0;
}
```
In my test case, the size of test.rar after decompression is 2416865 byte, but the progress stops at 2274870 byte. It seems that some data is not being recorded.
It would be worse if my test file was smaller, the progress callback function would only print 0.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
By chance, did you test whether the 7-zip GUI has the same issue while extracting the same RAR archive?
Bit7z calls the progress callback when 7-zip DLL calls it; the library doesn't do much more, so I suspect that it's 7-zip that doesn't inform bit7z about the last bytes extracted.
I did some checks and had the same issue with the 7-zip GUI, leading me to think it's a 7-zip issue even further.

**Comment by liugantang** [comment]
I checked the results of 7z-gui and this is indeed a 7z issue.
