### ISSUE TITLE
[Feature Request]: provide an overwrite mode when decompressing the file

### ISSUE THREAD

**Issue by xiaohuohumax** [rikyoz/bit7z#116]
### Feature description

Hi !

english is not good. excuse me 😅.

bit7z version: 

v4.0.0-beta

my code:

```cpp
Bit7zLibrary lib{ "./7z.dll" };
BitFileExtractor ext{ lib, BitFormat::Auto };
// close RetainDirectories
ext.setRetainDirectories(false);

ext.extract("test.zip", "d:/test");
```
my zip structure

```text
// test.zip
test
 ├── 1.txt
 └── 1f
     ├── 1.txt
     └── 2f
         └── 1.txt
```

unzip result (files with the same name will be overwritten)

```text
1.txt
```

i find in resource code (fileextractcallback.cpp => getOutStream)

```cpp
// ...
if (fs::exists(mFilePathOnDisk, ec) && !fs::remove(mFilePathOnDisk, ec)) {
  mErrorMessage = kCannotDeleteOutput;
  return E_ABORT;
 }
// ...
```

7zip commands (7z.exe e -ao[a | s | t | u ])

when I use this library, I can't find a way to set the override mode. Is there any way?

Thanks! 👍💕

### Additional context

```cpp
enum struct OverwriteMode {
    Overwrite = 0,
    Skip,
    RenameExtract,
    RenameExist
};

BitFileExtractor ext{ lib, BitFormat::Auto };
ext.setOverwriteMode(OverwriteMode::Overwrite);
```

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
> english is not good. excuse me 😅.

Mine too, no problem! :D 

>  I can't find a way to set the override mode. Is there any way?

Unfortunately, there's no direct way to set it, at least for now.

I think that `OverwriteMode::RenameExist` might be achievable by using BitFileExtractor's fileCallback:

```cpp
ext.setFileCallback( []( const string& path ) {
   auto full_path = output_path + "/" + path;
   // You might emulate OverwriteMode::RenameExist by checking if full_path exists,
   // and in case, rename it.
   // The file callback is called before the overwrite code.
}
```

I will definitely implement such a feature as soon as possible, but it will require quite a bit of refactoring of the library's internal code, so I'm not sure it will make it into the stable v4.0.
Anyway, thank you for your suggestion!
