### ISSUE TITLE
How to unzip only one file inside of an archive?

### ISSUE THREAD

**Issue by luochuanyuewu** [rikyoz/bit7z#12]
As the tile said. I have no clue how to do it. Please help. thanks!

**Comment by rikyoz** [comment]
Hi. The actual version of bit7z doesn't support this functionality: you can only extract the entire content of the archive! I plan to add the possibility of choosing which file to extract in a next version of the library. At the moment I'm quite busy in solving other issues, so I don't know when I'll finally implement this feature.

**Comment by luochuanyuewu** [comment]
Thanks for replying. it's good to know that you will do it in next release.
