### ISSUE TITLE
[Feature Request]: Allow parent cmakelists to specify external path to the lzma-sdk

### ISSUE THREAD

**Issue by RichardTea** [rikyoz/bit7z#126]
### Feature description

Currently, `7ZIP_SOURCE_DIR` is a private 'normal' variable, so the user cannot easily override it to point to some other copy of the lzma-sdk

Please can this be changed to be a CACHE variable for easier configuration, eg:

```
set( BIT7Z_EXTERNAL_LIBS_DIR "${PROJECT_SOURCE_DIR}/third_party" CACHE PATH "Third Party")
set( BIT7Z_7ZIP_SOURCE_DIR "${EXTERNAL_LIBS_DIR}/7-zip" CACHE PATH "7-Zip lzma-sdk")
```

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Implemented in [v4.0.0](https://github.com/rikyoz/bit7z/releases/tag/v4.0.0).

Now `BIT7Z_7ZIP_SOURCE_DIR` is called `BIT7Z_CUSTOM_7ZIP_PATH`.
