### ISSUE TITLE
How to get file detail informations in the zip

### ISSUE THREAD

**Issue by hcaihao** [rikyoz/bit7z#13]
How to get file modify date, zipped size, original size, crc value? such as winrar does.

**Comment by rikyoz** [comment]
This feature is not yet supported by bit7z, but it will be implemented in future versions!

**Comment by hcaihao** [comment]
When will the new version release? Bit7z is the most perfect 7z wrapper yet,  I'm very expect for this feature! Thanks!

**Comment by rikyoz** [comment]
Unfortunately, at the moment I'm quite busy with other works, but I'll try to release a new bit7z version by the end of May. This also depends on whether I will be able to quickly solve all the issues of the project or not; anyway, I'll do my best!
Thank you for your appreciation!
