### ISSUE TITLE
[Bug]: bit7z::BitFormat::Zip extract Exception

### ISSUE THREAD

**Issue by TimelifeCzy** [rikyoz/bit7z#135]
### bit7z version

3.2.x

### 7-zip version

v22.01

### 7-zip shared library used

7za.dll / 7za.so

### Compilers

MSVC

### Compiler versions

vs2019

### Architecture

x86

### Operating system

Windows

### Operating system versions

20H2

### Bug description

Zip:

`

		bit7z::Bit7zLibrary lib(str7zFullPath.c_str());
		std::shared_ptr<bit7z::BitExtractor> extractor = nullptr;
                extractor = std::make_shared<bit7z::BitExtractor>(lib, bit7z::BitFormat::Zip);
                extractor->extract(strResPath.GetString(), strDest.GetString());

`

Error: extractor->extract catch{ Exceptional }

7z  

`
                extractor = std::make_shared<bit7z::BitExtractor>(lib, bit7z::BitFormat::SevenZip);
` 

Success

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Unfortunately, I'm not able to reproduce your issue.
What does the exception message say?
Are you sure that the file you're trying to extract is a Zip file and not a 7z archive?
Thanks

**Comment by rikyoz** [comment]
Hi!
The problem is in the DLL you're using: `7za.dll` supports only the 7z format.
For extracting also Zip archives, you should use the `7z.dll`.
You can check the formats and features supported by all the 7-zip DLLs on this page: https://github.com/rikyoz/bit7z/wiki/7z-DLLs

**Comment by TimelifeCzy** [comment]
Thank You

**Comment by rikyoz** [comment]
You're welcome!
