### ISSUE TITLE
Collision of fs namespace

### ISSUE THREAD

**Issue by ra-dave** [rikyoz/bit7z#141]
I'm trying to utilize bit7z in our product code to evaluate it.  I am only using bitarchivewriter.hpp currently.  I am getting a namespace collision with the fs namespace as our code also is using that namespace.  I'm not sure yet why it's colliding, isn't bit7z's usage of that namespace an internal thing?

**Comment by rikyoz** [comment]
Uhm strange!

> isn't bit7z's usage of that namespace an internal thing?

Yes, it is, but unfortunately, there are some "semi-internal" classes that belong to the public API and need to use `fs::path`, hence that namespace had to be declared in a public header too.

I have some possible solutions to this, but I need to verify which might be the best.

Anyway, thanks for pointing out this issue!

**Comment by rikyoz** [comment]
Fixed in [v4.0.0](https://github.com/rikyoz/bit7z/releases/tag/v4.0.0).
