### ISSUE TITLE
[Bug]: MSVC2015 build failed with BIT7Z_AUTO_FORMAT

### ISSUE THREAD

**Issue by wang-zuxian** [rikyoz/bit7z#173]
### bit7z version

4.0.x

### Compilation options

BIT7Z_AUTO_FORMAT

### 7-zip version

v23.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

MSVC

### Compiler versions

MSVC2015

### Architecture

x86

### Operating system

Windows

### Operating system versions

Windows10

### Bug description

Build a dll link bit7z.lib with BIT7Z_AUTO_FORMAT then show link error

16:21:57:379	2>bit7z.lib(bitinputarchive.obj) : error LNK2001: 无法解析的外部符号 "class bit7z::BitInFormat const & __cdecl bit7z::detect_format_from_extension(class ghc::filesystem::path const &)" (?detect_format_from_extension@bit7z@@YAABVBitInFormat@1@ABVpath@filesystem@ghc@@@Z)
16:21:57:379	2>bit7z.lib(bitinputarchive.obj) : error LNK2001: 无法解析的外部符号 "class bit7z::BitInFormat const & __cdecl bit7z::detect_format_from_signature(struct IInStream *)" (?detect_format_from_signature@bit7z@@YAABVBitInFormat@1@PAUIInStream@@@Z)
fatal error LNK1120: 2 个无法解析的外部命令

### Expected behavior

internal/formatdetect.cpp:

#ifdef BIT7Z_AUTO_FORMAT
#include <algorithm>
#include "internal/formatdetect.hpp"

change to

#include "internal/formatdetect.hpp"
#ifdef BIT7Z_AUTO_FORMAT
#include <algorithm>

then build success.
THANKS.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Thank you for reporting the issue!
Yesterday, I pushed a fix to the `develop` branch.
I'll release a new version of bit7z with the fix soon.

**Comment by rikyoz** [comment]
Fixed in [v4.0.4](https://github.com/rikyoz/bit7z/releases/tag/v4.0.4).
