### ISSUE TITLE
[Feature Request]: how ot set AES-128,AES-256 encrypted

### ISSUE THREAD

**Issue by hakwolf** [rikyoz/bit7z#174]
### Feature description

how can I use this lib to set 7Z ,zip compress file as none, AES-128,AES-256 encrypted.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
To change the encryption method to be used with the Zip format, you can use the `setFormatProperty` and pass to it the native 7-zip format option [`em`](https://7-zip.opensource.jp/chm/cmdline/switches/method.htm#Zip) as follows:

```cpp
Bit7zLibrary lib{};
BitFileCompressor compressor( lib, BitFormat::Zip );
compressor.setFormatProperty( L"em", L"AES256" ); // ZipCrypto, AES128, AES192, AES256
compressor.setPassword( "password" );
compressor.compressFile( "path/to/file.txt", "path/to/archive.zip" );
```

No encryption is performed by default if you don't specify a password.
If you specify a password, the default encryption method `ZipCrypto` is used unless you explicitly set a different method via `setFormatProperty`.

Please note that the `setFormatProperty` only accepts wide string literals (regardless of the CMake option `BIT7Z_USE_NATIVE_STRING`).

**Comment by hakwolf** [comment]
i will both use 7z and zip format . if I use choose 7z format, use method is any diffrent then zip?
```
BitFileCompressor compressor{ lib, BitFormat::SevenZip };
compressor.setFormatProperty( L"em", L"AES256" ); // ZipCrypto, AES128, AES192, AES256
compressor.setPassword( "password" );
compressor.compressFile( "path/to/file.txt", "path/to/archive.zip" );
```

**Comment by rikyoz** [comment]
Unfortunately, the 7z format doesn't support any other encryption method than AES256.
As such, 7-zip doesn't accept the `em` flag when using the 7z format and returns an error during compression, causing bit7z to throw an exception to notify the user.
