### ISSUE TITLE
[Feature Request]: RenameOutput

### ISSUE THREAD

**Issue by lbxx11** [rikyoz/bit7z#179]
### Feature description

Hi，sorry for bothering, but wondering is there a clear timeline for `RenameOutput` Mode?

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
My plan is to add `OverwriteMode::RenameOutput` in the next v4.1 release (along with other features).
As for a clear timeline, I'm currently working on expanding the unit tests, and after that, I'll begin working on new features like this.
I don't have a precise deadline, but I hope to finish as soon as possible!

**Comment by lbxx11** [comment]
Thanks for your reply!
All the best
