### ISSUE TITLE
[Feature Request]: Extracting files whose names contain forbidden characters

### ISSUE THREAD

**Issue by AndrewGsnv** [rikyoz/bit7z#190]
### Feature description

Is it possible to somehow implement the extraction of files whose names contain characters prohibited for the Windows file system, for example ":" with their replacement by "_"? 
Thanks.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Yes, you can enable the path sanitization of characters prohibited on Windows by using the CMake option `-DBIT7Z_PATH_SANITIZATION=ON`.
All invalid characters will be replaced by `_`, as in your example.
