### ISSUE TITLE
Do I need to build 7zip myself?

### ISSUE THREAD

**Issue by TrueWodzu** [rikyoz/bit7z#191]
Hi, thank you for the library! 

It is my first day with it and I've read about compatibility issues with 7zip versions. I see that the library is downloading 7zip sources, but does not build them. Does it mean that I should build them on my own or am I missing something?

PS. I've noticed that for version 4.0.5 (tag) CMake states: "Target Version: 4.0.4"

**Comment by TrueWodzu** [comment]
Hi @rikyoz thank you for the detailed answer. I am sorry, I wasn't very clear regarding the operating system. I wanted to use Linux, however the problem is that (as for my understanding) there are no official build scripts for 7-zip for Linux. I wanted to build shared library for version 23.01.
Have you tried to build 7-Zip on Linux?

**Comment by TrueWodzu** [comment]
BTW: I've found precompiled .so files for the newest version: https://packages.ubuntu.com/noble/7zip
The problem is that it probably depends on other new packages that are not available on Ubuntu 22.04 which I am suing currently.

**Comment by rikyoz** [comment]
Hey, sorry for the late reply!

>  I am sorry, I wasn't very clear regarding the operating system. I wanted to use Linux, however the problem is that (as for my understanding) there are no official build scripts for 7-zip for Linux. I wanted to build shared library for version 23.01.

I see. Building the 7-Zip library for Linux is actually fairly easy.
In the source code of 7-Zip, you go to the directory `CPP/7zip/Bundles/Format7zF/` and from there you run the command `make -j -f ../../cmpl_gcc.mak` (if you want to use GCC) or `make -j -f ../../cmpl_clang.mak` (if you want to use Clang).
After the build finishes, you will find the `7z.so` in a sub directory `CPP/7zip/Bundles/Format7zF/`.

For example:
```bash
> cd $7ZIP_SRC/CPP/7zip/Bundles/Format7zF/
> make -j -f ../../cmpl_gcc.mak
...
> ls -lh b/g/7z.so
-rwxrwxrwx 1 rikyoz rikyoz 2.7M Feb 28 08:47 b/g/7z.so
```

> or even better to build 7-zip optionally during installation of bit7z. But I guess this will be a lot of work

In the midterm I plan to write some documentation in the Wiki on how to build the libraries on all the supported platforms. In the long term, yeah, I plan to make it easy to build the libraries, possibly within the same process of building bit7z.

**Comment by TrueWodzu** [comment]
Hey @rikyoz thank you very much, I would never figure out that the build script is there!

**Comment by rikyoz** [comment]
You're welcome! :)
