### ISSUE TITLE
[Feature Request]: Is "tstring_to_path" forgotten here?

### ISSUE THREAD

**Issue by singlebear** [rikyoz/bit7z#199]
### Feature description

![image](https://github.com/rikyoz/bit7z/assets/48552037/79a513a3-a4d2-4763-8972-b5728440d64b)
I need to convert character encoding from native to UTF8. But I found that the input parameters std::map and std::vector behave differently. When examining the source code, it is found that std::vector does not handle "tstring_to_path". Is that what it's supposed to be?

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> Is that what it's supposed to be?

Uhm no, there's definitely a missing `tstring_to_path` call there, nice catch!

I just pushed a [commit](2d3afb70b28c0d566f7ce2354a752bd5d94f5b73) to the new branch `hotfix/v4.0.7` that fixes it. The next patch version will contain the fix.
Thank you for reporting this issue.
