### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wzwangyike** [rikyoz/bit7z#201]
### bit7z version

4.0.x

### Compilation options

BIT7Z_AUTO_FORMAT, BIT7Z_GENERATE_PIC, BIT7Z_USE_NATIVE_STRING

### 7-zip version

v23.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

GCC

### Compiler versions

4.9.2

### Architecture

x86_64

### Operating system

Linux

### Operating system versions

UOS20(1060)

### Bug description

BitArchiveReader archive(lib, strCompressFile); run crash.

### Steps to reproduce

1. i use centos6 gcc 4.9.2 to build 7z.so , bit7z.a ,and xxx.so(using bit7z.a)
2. i push xxx.so to UOS and run to BitArchiveReader archive(lib, strCompressFile); 
3. it will crash with iUnknow.Release.
4. 
<img width="503" alt="image" src="https://github.com/rikyoz/bit7z/assets/28339291/95a92547-0a1d-4ba2-851f-824f7dca9284">
this is the crash info.

the point 0x7fffc806e010 is CFileInStream .

the 0x7fffc806e010 frist ~ is tmp CFileInStream in make_com function

I ues the last master's code , also have this crash.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> i use centos6 gcc 4.9.2 to build 7z.so , bit7z.a ,and xxx.so(using bit7z.a)

Do you build the 7z.so from the 7-Zip or from p7zip?

Does building bit7z with the option `BIT7Z_USE_LEGACY_IUNKNOWN` enabled (i.e., `-DBIT7Z_USE_LEGACY_IUNKNOWN=ON`) fix the issue?

**Comment by wzwangyike** [comment]
Hi!

> Are you building the 7z.so from the 7-Zip project or from p7zip?

i build the biit7z auto download the 7z project, and build path /7-zip/CPP/7zip/Bundles/Format7zF/ use `make -f makefile.gcc` , get the 7z.so

this is the build option 
![image](https://github.com/rikyoz/bit7z/assets/28339291/05adf2fe-e3c5-40b0-b70b-7b2cd746363d)

i copy the auto download `_deps\7-zip-src` to `third_party/7-zip` and use the path.
and append build flag `add_compile_options(-fPIC)`

i use test code by :
```c++
#include <iostream>
#include "bitarchivereader.hpp"
using namespace bit7z;
#include <dlfcn.h>
std::string GetCurrentPath()
{
	Dl_info dl_info;
	dladdr((void*)GetCurrentPath, &dl_info);
	std::string str = dl_info.dli_fname;
	return str.substr(0, str.find_last_of('/') + 1);
}

std::string Get7zPath()
{
	std::string str = GetCurrentPath();
	return str + "7z.so";
}

int main(int argc, char *argv[])
{

Bit7zLibrary lib(Get7zPath());
BitArchiveReader archive(lib, argv[1]);
    system("chcp 65001");
    return 0;
}
```
and run this test. it also run error.
![image](https://github.com/rikyoz/bit7z/assets/28339291/c36ec291-73a9-4916-99af-87ae2f9791f0)


i try to run at build OS . centos6. it also error.

**Comment by wzwangyike** [comment]
i change cmake to case this bug..so sorry fot this bug

**Comment by rikyoz** [comment]
No problem!

Thank you for using this library! 🙏
