### ISSUE TITLE
[Bug]: Some zip file names are garbled

### ISSUE THREAD

**Issue by lz990377023** [rikyoz/bit7z#207]
### bit7z version

4.0.x

### Compilation options

BIT7Z_7ZIP_VERSION

### 7-zip version

v23.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

Clang

### Architecture

x86_64

### Operating system

macOS

### Bug description

<img width="871" alt="截屏2024-05-04 13 27 52" src="https://github.com/rikyoz/bit7z/assets/10387119/dc332e8f-a510-45d8-9c20-9be47d80e7ff">
<img width="1212" alt="截屏2024-05-04 13 33 17" src="https://github.com/rikyoz/bit7z/assets/10387119/86f9180c-c74d-4fca-94fb-867c19674c02">

Hello, I used mac to decompress zip and found some Chinese garbled characters in the package, I don't know what the cause is, is there a problem with the string decoding Settings

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
>  is there a problem with the string decoding Settings

As far as I know, there shouldn't be any problem.
7-Zip always uses wide strings internally, and that `bstrValue` is exactly the string that 7-Zip reports to bit7z, without any modification.
On Linux and macOS, bit7z then needs to convert/decode these wide strings into narrow strings; to do this, the library uses the C++ standard way of narrow string conversion, i.e:
```cpp
std::wstring_convert< std::codecvt_utf8< wchar_t >, wchar_t > converter;
return converter.to_bytes( wideString, wideString + size ); // std::wstring to std::string
```
So I don't think that the problem is on bit7z's side, but I'll try to investigate it anyway!

**Comment by lz990377023** [comment]
Thanks for your answer, I have tried to convert wstring to string, but it is still garbled
![截屏2024-05-05 13 54 21](https://github.com/rikyoz/bit7z/assets/10387119/c25cfbb0-4eed-44fb-b335-78dbcde2cb0b)
The correct text is the picture below
![截屏2024-05-05 13 55 59](https://github.com/rikyoz/bit7z/assets/10387119/7234d874-e152-4d3a-b176-4515160cec8c)

**Comment by rikyoz** [comment]
> I have tried to convert wstring to string, but it is still garbled

Sorry, I meant that bit7z already performs the conversion, so there's no need to do a string -> wstring -> string conversion.

Anyway, I did some tests, and I was able to replicate the issue.
It seems to happen only on Zip archives created using the macOS's native compress tool (the one from the right-click context menu).
![image](https://github.com/rikyoz/bit7z/assets/1334291/49c55158-6376-467d-8e21-4c384c909066)
![image](https://github.com/rikyoz/bit7z/assets/1334291/7521a9b5-78b1-4f96-8d3e-55c1f8e2750d)

If however the |ip archive is created via 7-Zip's CLI `7zz`, the name of the item is correctly decoded:
![image](https://github.com/rikyoz/bit7z/assets/1334291/9a6eaece-93e4-427c-918d-0b2ec5253ebd)
![image](https://github.com/rikyoz/bit7z/assets/1334291/a6bab5c0-92fc-481e-a93e-12a640d2a2aa)

As I said, I don't think this is a bug on bit7z side: it is the `7z.so` that reports the item name differently in these cases, for some reasons.

Though, the 7-Zip's CLI seems to perform some further string decoding with respect to the shared library, as the `7zz` tool always displays the correct name:
![image](https://github.com/rikyoz/bit7z/assets/1334291/00bd43b7-c66f-45f3-9c29-f844ce70cd08)

I'll investigate what decoding is performed by `7zz` and try to implement it also in bit7z.

**Comment by lz990377023** [comment]
Thanks again for your reply, I will also try to see the processing of 7zz and look forward to updating the string decoder to bit7z
