### ISSUE TITLE
[Bug]: Inconsistent encoding of string parameter

### ISSUE THREAD

**Issue by hcaihao** [rikyoz/bit7z#217]
### bit7z version

4.0.x

### Compilation options

BIT7Z_7ZIP_VERSION

### 7-zip version

v23.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

MSVC

### Architecture

x86_64

### Operating system

Windows

### Operating system versions

Windows 11

### Bug description

```
std::string CompressFiles(const std::vector< std::string >& inPaths, const std::string& outFile)
{
		try
		{
			Bit7zLibrary lib{ "7z.dll" };
			BitFileCompressor compressor{ lib, BitFormat::Zip };
			compressor.setOverwriteMode(OverwriteMode::Overwrite);
			compressor.compress(inPaths, outFile);
		}
		catch (const bit7z::BitException& ex) {
			result = ex.what();
		}
		
		return result;
}
```
if inPaths inlcude unicode, std::string "must" be encoded by gbk(), otherwise throw "Invalid path: The system cannot find the path specified."

```
std::string CompressDirectory(const std::string& inDir, const std::string& outFile)
{
	std::string result;

	try
	{
		Bit7zLibrary lib{ "7z.dll" };
		BitFileCompressor compressor{ lib, BitFormat::Zip };
		compressor.compressDirectory(inDir, outFile);
	}
	catch (const bit7z::BitException& ex) {
		result = ex.what();
	}

	return result;
}
```

if inDir inlcude unicode, std::string "must" be encoded by utf8, otherwise throw "Invalid path: The system cannot find the path specified."

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
What version of bit7z are you using?

> if inPaths inlcude unicode, std::string "must" be encoded by gbk(), otherwise throw "Invalid path: The system cannot find the path specified."

In the latest v4.0.7, I [fixed](https://github.com/rikyoz/bit7z/commit/2d3afb70b28c0d566f7ce2354a752bd5d94f5b73) a similar issue, so this is strange if you happen to use the latest version of the library.

> if inDir inlcude unicode, std::string "must" be encoded by utf8, otherwise throw "Invalid path: The system cannot find the path specified."

By default bit7z expects UTF-8 encoded `std::strings'. So the second example behaves correctly.
