### ISSUE TITLE
[Feature Request]: VS2010

### ISSUE THREAD

**Issue by zpjjimmie** [rikyoz/bit7z#220]
### Feature description

If I Want Use it in VS2010, which version of code should I use (because it support msvc2015 or later, but I want to compile code myself in vs2010)

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
The last version of bit7z that supported VS2010 was the [v2.1.0](https://github.com/rikyoz/bit7z/releases/tag/v2.1.0).
Please note that the API of this version of the library is slightly different from the latest v4, as the API has changed over time and many features have been added since its release.

**Comment by zpjjimmie** [comment]
> Hi! The last version of bit7z that supported VS2010 was the [v2.1.0](https://github.com/rikyoz/bit7z/releases/tag/v2.1.0). Please note that the API of this version of the library is slightly different from the latest v4, as the API has changed over time and many features have been added since its release.

Thank you for replay, I tried this version,  but also can't compile, and the lib gived in this link is vs2015 alse, maybe have a older version?

**Comment by rikyoz** [comment]
As far as I can remember, v2.1.0 should compile. Unfortunately I don't have access to a system with VS2010 to check why it doesn't compile.
The [v2.0.0](https://github.com/rikyoz/bit7z/releases/tag/v2.0.0) should also compile, as this version added support for MSVC 2010 and 2012.
Unfortunately, at the time I only provided precompiled versions of the library for MSVC 2015.
