### ISSUE TITLE
[Bug]: Mingw cross compile fails

### ISSUE THREAD

**Issue by yildiz-online** [rikyoz/bit7z#222]
### bit7z version

4.0.x

### 7-zip version

v23.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

MinGW

### Architecture

x86_64

### Operating system

Linux

### Bug description

Cross compiling from linux to windows is leading to:
/bit7z/bitwindows.hpp:21:10: fatal error: Windows.h: No such file or directory

Renaming to #include <windows.h> fixes the issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Thank you for reporting this issue.
I just pushed a commit to the `master` branch that fixes it.

**Comment by yildiz-online** [comment]
Thank you! Issue can be closed as fixed.
