### ISSUE TITLE
[Bug]: Failed to test the archive: Unsupported method with RAR archives

### ISSUE THREAD

**Issue by FoX4-C** [rikyoz/bit7z#242]
### bit7z version

4.0.x

### Compilation options

BIT7Z_AUTO_FORMAT, BIT7Z_GENERATE_PIC, BIT7Z_USE_LEGACY_IUNKNOWN

### 7-zip version

v16.02

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

GCC

### Compiler versions

GCC 9.4

### Architecture

x86_64

### Operating system

Linux

### Operating system versions

Ubuntu 20.04

### Bug description

Hello!
When i'm trying to extract the files from RAR archive using BitArchiveReader or BitFileExtractor i'm receiving `Failed to test the archive: Unsupported method.`. When i build and run the tests included in library i see that all tests with RAR extension if failed.

The same behaviour i have if i set BIT7Z_7ZIP_VERSION to 16.02.
Also i tried `bit7z::BitFormat::Auto` and `bit7z::BitFormat::RAR5` and still gettting the same exception.

unrar and p7zip-rar packets are installed on my machine, and if i try to extract the data using 7z tools it works fine.

Getting metainformation about RAR archives works fine.
For 7z and zip files everything works fine.
The library build-in as third-party in project.

Could you help me please and point what i'm doing wrong.
Thanks!

### Steps to reproduce

Call methods `extractTo` or `test` for RAR archive

### Expected behavior

Data is extracted from RAR achives without throwing a exception

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Yeah, unfortunately bit7z doesn't support RAR archives when using p7zip, even if the p7zip-rar plugin is installed.
I have researched the issue in the past, but could not find any documentation in p7zip on how to use the plugin for RAR archives; I also did some experiments, but they were unsuccessful.
In the end, I mostly gave up, as I didn't have time to investigate the problem further, especially after 7-Zip added support for Linux and p7zip became obsolete.
Anyway, this is only a problem when using p7zip. If you use 7-Zip's 7z.so, you won't have any problem with RAR archives (as it doesn't need an additional plugin to work).
Unfortunately, 7-Zip doesn't provide a prebuilt 7z.so right away, but it is easy to build one (I can provide the steps needed, in case).
Sorry, I forgot to put all these details in the README or in the Wiki, I'll update them in the next release to make it clearer.

**Comment by FoX4-C** [comment]
O, didn't know that. Thank's a lot for a quick answer!

>  I'll update them in the next release to make it clearer.

That would be great )

> If you use 7-Zip's 7z.so, you won't have any problem with RAR archives

I have one more question: does official 7z API supports decryption of RAR archives? Cause i'm investigating using bit7z instead of libarchive in project (they don't have a support for any archives decryprion but 7z).

**Comment by rikyoz** [comment]
> Thank's a lot for a quick answer!

No problem!

> I have one more question: does official 7z API supports decryption of RAR archives? Cause i'm investigating using bit7z instead of libarchive in project (they don't have a support for any archives decryprion but 7z).

Yes, 7-Zip/bit7z API supports decryption of RAR archives, both normally encrypted and header encrypted ones.

**Comment by FoX4-C** [comment]
I built 7z from sources (23.01 taken from [here](https://www.7-zip.org/download.html)) using the make command:
`make -j -f ../../cmpl_gcc.mak`
from CPP/7zip/Bundles/Format7zF folder.

Now i have segmentation fault when calling the CMyComPtr destructor from BitInputArchive constructor.

**Comment by FoX4-C** [comment]
Disabling BIT7Z_USE_LEGACY_IUNKNOWN helped

**Comment by FoX4-C** [comment]
Disabling BIT7Z_USE_LEGACY_IUNKNOWN helped.
Found description about compatibility and BIT7Z_USE_LEGACY_IUNKNOWN in documentation.

Extracting encrypted rar works.
Thansk for helping!
