### ISSUE TITLE
Compile x86 under 64bit Windows.

### ISSUE THREAD

**Issue by octalflow** [rikyoz/bit7z#244]
### Feature description

How to compile 32bit x86 ?

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Generally, the answer depends on the compiler you're using.
With MSVC, for example, you need to pass the target [platform selection parameter](https://cmake.org/cmake/help/latest/generator/Visual%20Studio%2017%202022.html#platform-selection) to CMake when configuring the project: `cmake -G "Visual Studio 17 2022" -A Win32` for x86 using MSVC 2022.

**Comment by octalflow** [comment]
thank you !!!

**Comment by octalflow** [comment]
.
