### ISSUE TITLE
[Documentation]: Mention getErrorCode in upgrading section

### ISSUE THREAD

**Issue by levicki** [rikyoz/bit7z#245]
### Feature description

The upgrading section [here](https://github.com/rikyoz/bit7z/tree/v4.0.0?tab=readme-ov-file#-upgrading-from-bit7z-v3-to-v4) does not mention that `BitException` no longer has `getErrorCode()` and what it has been replaced with.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
You are right, I forgot to add this change to the list.
Thanks for pointing this out, I will update the README as soon as possible!

**Comment by levicki** [comment]
@rikyoz No worries man, I upgraded my project from 3.1.1 to 4.0.8 without a hitch. I hope you are doing fine, thanks again for writing this library.

**Comment by rikyoz** [comment]
> I upgraded my project from 3.1.1 to 4.0.8 without a hitch.

Glad to hear the upgrade went smoothly!

> I hope you are doing fine, thanks again for writing this library.

Thank you for your kind words! I'm doing well, hope you are too. 
Thanks for keeping using bit7z! 🙏

**Comment by rikyoz** [comment]
Fixed the README in [v4.0.9](https://github.com/rikyoz/bit7z/releases/tag/v4.0.9).

**Comment by levicki** [comment]
> Fixed the README in [v4.0.9](https://github.com/rikyoz/bit7z/releases/tag/v4.0.9).

Thanks for letting me know, I just updated my library to 4.0.9 and 24.09 SDK.
