### ISSUE TITLE
BitArchiveReader

### ISSUE THREAD

**Issue by octalflow** [rikyoz/bit7z#252]
### Feature description

BitArchiveReader( const Bit7zLibrary& lib,
    const std::vector< byte_t >& inArchive,
    const BitInFormat& format BIT7Z_DEFAULT_FORMAT,
    const tstring& password = {} );

After create it. Can I remove inArchive(vector<byte_t>) ?
If not, How about BitArchiveReader(, std::istream& inArchive,, ) ?

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> After create it. Can I remove inArchive(vector<byte_t>) ?
> If not, How about BitArchiveReader(, std::istream& inArchive,, ) ?

Sorry, I'm not sure I understand what you're asking.
`BitArchiveReader` is a RAII class, and to simplify, it stores and uses a reference to the buffer/stream.
The `BitArchiveReader` instance you create may still need to read from the buffer/stream, so it needs to outlive it. If you remove the buffer or close the stream and the reader is still alive, it may not work as expected (in the best case, any operation called on the reader may throw an exception).
So you should really first make sure that the reader goes out of scope, and then you can remove the buffer or close the stream.

For example:
```cpp
std::vector<byte_t> buffer;
// Here you load an archive to the buffer.
{
    BitArchiveReader reader{ lib, buffer };
    // Do something with reader.
} // The reader goes out of scope, closing the opened archive.
// Now the buffer can be removed (e.g., it can go out of scope or you can call `buffer.clear()`).
```

**Comment by octalflow** [comment]
Thanks.
