### ISSUE TITLE
[Bug]: Cannot be used under QT 6.8

### ISSUE THREAD

**Issue by canghaiwuhen** [rikyoz/bit7z#255]
### bit7z version

4.0.x

### 7-zip version

v23.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

MinGW

### Compiler versions

QT 6.8 mingw13.1

### Architecture

x86_64

### Operating system

Windows

### Bug description

![image](https://github.com/user-attachments/assets/7ff99ff0-de08-4e90-a747-69433e86bbf2)
I compiled the lib with mingw 13.1 under qt 6.8, and then created a demo project under qt 6.8. The compilation kept reporting errors.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by canghaiwuhen** [comment]
7z used 24.08 is also error
The lib library is compiled with vs2022, and then a project is created under qt. The vs2022 compiler is selected. The compilation fails under qt. Switch to vs2022 and use the qt plug-in. The compilation succeeds.

The lib library is compiled with mingw 13.1 in qt6.8, and then a project is created under qt. The mingw compiler is used and the compilation fails.

**Comment by rikyoz** [comment]
Hi!
Are you liking the `oleaut32` library in your Qt demo project?
For example, in the project's `.pro` file you should to something like this:
```qmake
LIBS += -loleaut32
```
Bit7z depends on this library, as specified in the README [here](https://github.com/rikyoz/bit7z?tab=readme-ov-file#user-content-fn-1-07c945edec0af75b0b9392985a5334c7) and in the Wiki [here](https://github.com/rikyoz/bit7z/wiki/Building-the-library).

**Comment by canghaiwuhen** [comment]
> ```qmake
> LIBS += -loleaut32
> ```

This is not the problem
LIBS += -L -lOleAut32 -lUser32
I have added it in qt, but it still gives an error
I have seen this description, and it works without adding it in vs2022

**Comment by canghaiwuhen** [comment]
![image](https://github.com/user-attachments/assets/28b0983a-734b-4cf2-bd4f-2a0bc2b68159)

**Comment by canghaiwuhen** [comment]
From the error message, it seems like a problem with the function in the lib compiled by mingw?

**Comment by rikyoz** [comment]
> it works without adding it in vs2022

Probably because oleaut32 is already linked somewhere else.

> it seems like a problem with the function in the lib compiled by mingw?

yeah, I forgot that some versions of MinGW require also to link the `libuuid`, so it would require a line like this:
```qmake
LIBS += -loleaut32 -luuid
```
I will update the documentation accordingly.

**Comment by canghaiwuhen** [comment]
> > it works without adding it in vs2022
> 
> Probably because oleaut32 is already linked somewhere else.
> 
> > it seems like a problem with the function in the lib compiled by mingw?
> 
> yeah, sorry, I forgot that some versions of MinGW require also to link the `libuuid` library, so they would require a line like this:
> 
> ```qmake
> LIBS += -loleaut32 -luuid
> ```
> 
> I will update the documentation accordingly.

yeah, it's work!
Thanks!
