### ISSUE TITLE
Large Memory Pages support

### ISSUE THREAD

**Issue by levicki** [rikyoz/bit7z#26]
7-Zip DLLs supports using Large Memory Pages as a speed optimization.

It would be nice if we could request this to be used when possible if it already isn't used by default.

The 7-Zip API to call is `SetLargePageMode`.

**Comment by rikyoz** [comment]
Good idea, I think I'll add the possibility to call the `SetLargePageMode` function from the `Bit7zLibrary` class.

Thank you for your suggestion!
