### ISSUE TITLE
[Bug]: arc.extractTo horrendous performance for .7z vs .zip

### ISSUE THREAD

**Issue by sjellenoff** [rikyoz/bit7z#261]
### bit7z version

4.0.x

### 7-zip version

v23.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

MSVC

### Compiler versions

msvc 2015 prebuilt

### Architecture

x86 (non-mt)

### Operating system

Windows

### Operating system versions

Windows 7

### Bug description

I've been loving bit7z for almost a year now and have been using it for basic archive info and extraction.
Initially I only supported .zip files, but recently added .7z support by changing the format passed to BitArchiveReader.

When using a 36MB zip file my project extracts the files into memory in about a 1-2 seconds max. It's lightning fast.
When using the same file contents in a 29MB .7z file, it takes 15-20 or seconds! WTF?
Code is simply this in a loop for each file. It extracts about 15 files needed out of 153 stored in the archive.
try
{
    arc.extractTo(i->file_contents, bufsize, i->index);
}
catch (const bit7z::BitException& ex)
{
    // Append to error msg
    strncat(errorMsg, ex.what(),BIT7Z_DLL_MAX_ERROR_STRING);
}

I'm using 4.0.5 and I read there was some compression time improvements in recent versions for .7z, but wasn't sure it applied to extraction. Plus it was mentioning only 10% improvements.. It would require orders of magnitude more performance to match the zip performance.

Any thoughts / suggestions. Am I the only one seeing this issue?

### Steps to reproduce

Call arc.extractTo() on 10-20 files ( 2MB each ) using .7z format. Time the complete extraction process.
Compare to same files using .zip format and compare. There is a massive difference in performance, 1-2 seconds vs 15-20 seconds.

### Expected behavior

Using arc.extractTo() for a .7z file should have similar performance to .zip file.

### Relevant compilation output

```shell
Using prebuilt mscv 2015
```

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by sjellenoff** [comment]
I just tested on 4.0.8 and performance issue is the same.

**Comment by rikyoz** [comment]
Hi!
Does the .7z archive use solid compression?
If so, this might explain the slow performance, as solid archives are really meant to be extracted in a single operation.
With this type of archive, extracting single files by index, as you do in your loop, is usually significantly slower.

A quick benchmark to show the difference using two ~29MB .7z archives with the same files, but one solid and one not:
```
[solid] extractTo std::map: 373ms
[solid] extractTo by index in loop: 11815ms
[non-solid] extractTo std::map: 360ms
[non-solid] extractTo by index in loop: 364ms
```

As you can see, extracting a solid archive in one go to a std::map is fast, but extracting each file in the archive by index (as you do in your code) is slow.

This is one of the drawbacks of using solid compression, because to extract a single file from a solid archive you have to process all the files before it. And doing this in a loop adds overhead at each iteration. Non-solid 7z archives do not have this problem, at the cost of (usually) larger file size.

If this is your case, there is no overhead on the bit7z side, the operation itself is slow, and unfortunately there's not much the library can do to improve performance.

**Comment by sjellenoff** [comment]
Thank you so much for your quick reply and insightful information.

I wasn't aware of the concept of a solid archive so thanks for educating me. :)
I implemented a quick test using the extractTo with map, and the extraction now takes 2.5 seconds, vs 15-20.. 

At first I was disappointed but then I approximated the extraction time using 7z GUI and it's about 2ish seconds, so your code is working just fine as you explained.

Appreciate your help and thanks for a great project, it's a pleasure to work with.

**Comment by sjellenoff** [comment]
Closing the issue, since the bug is not in your project, but rather with my implementation failing to consider handling a solid archive compressed .7z file as you pointed out. Thanks!

**Comment by rikyoz** [comment]
> Thank you so much for your quick reply and insightful information.

> I wasn't aware of the concept of a solid archive so thanks for educating me. :)

No problem!

> I implemented a quick test using the extractTo with map, and the extraction now takes 2.5 seconds, vs 15-20..

> At first I was disappointed but then I approximated the extraction time using 7z GUI and it's about 2ish seconds, so your code is working just fine as you explained.

Yeah, I do not rule out that there is room for performance improvement even in the method that extracts to an std::map. For example, inserting into the std::map itself might introduce some overhead.
I'll definitely work on improving it, for example by adding support to std::unordered_map or a custom data structure.

> Appreciate your help and thanks for a great project, it's a pleasure to work with.

> Closing the issue, since the bug is not in your project, but rather with my implementation failing to consider handling a solid archive compressed .7z file as you pointed out. Thanks!

You're welcome, and thank you for using the library!
