### ISSUE TITLE
[Feature Request]: Supporting the 7z dynamic library built from macOS.

### ISSUE THREAD

**Issue by coalooball** [rikyoz/bit7z#264]
### Feature description

I downloaded source codes of 7zip and run command below to acquire macOS dynamic library `m_arm64`
```sh
cd CPP/7zip/Bundles/Format7zF
make -j -f ../../cmpl_gcc_arm64.mak
```

After that, I used the sample code from bit7z:

```cpp
#include <bit7z/bit7z.hpp>
#include <bit7z/bitarchivereader.hpp>
#include <iostream>

int main() {
    try { // bit7z classes can throw BitException objects
        using namespace bit7z;

        Bit7zLibrary lib{ "/Users/somnambulatory/Downloads/7z2408-src/CPP/7zip/Bundles/Format7zF/b/m_arm64" };
        BitArchiveReader arc{ lib, "archive.7z", BitFormat::SevenZip };

        // Printing archive metadata
        std::cout << "Archive properties\n";
        std::cout << "  Items count: "   << arc.itemsCount() << '\n';
        std::cout << "  Folders count: " << arc.foldersCount() << '\n';
        std::cout << "  Files count: "   << arc.filesCount() << '\n';
        std::cout << "  Size: "          << arc.size() <<'\n';
        std::cout << "  Packed size: "   << arc.packSize() << "\n\n";

        // Printing the metadata of the archived items
        std::cout << "Archived items";
        for ( const auto& item : arc ) {
            std::cout << '\n';
            std::cout << "  Item index: "    << item.index() << '\n';
            std::cout << "    Name: "        << item.name() << '\n';
            std::cout << "    Extension: "   << item.extension() << '\n';
            std::cout << "    Path: "        << item.path() << '\n';
            std::cout << "    IsDir: "       << item.isDir() << '\n';
            std::cout << "    Size: "        << item.size() << '\n';
            std::cout << "    Packed size: " << item.packSize() << '\n';
            std::cout << "    CRC: " << std::hex << item.crc() << std::dec << '\n';
        }
        std::cout.flush();
    } catch (const bit7z::BitException& ex) {
        std::cerr << "Error: " << ex.what() << std::endl;
        return 1; 
    }

    return 0;
}

```

Output:

```sh
somnambulatory@somnambulatorys-Mac-mini bit7z % ./build/bit7z_example 
Error: Failed to load the 7-zip library: Bad file descriptor
```

It seems that the latest version `4.0.8` of bit7z still does not support loading dynamic libraries on macOS.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> I downloaded source codes of 7zip and run command below to acquire macOS dynamic library `m_arm64`

```cpp
Bit7zLibrary lib{ "/Users/somnambulatory/Downloads/7z2408-src/CPP/7zip/Bundles/Format7zF/b/m_arm64" };
```

I think the problem lies here: you're not specifying the correct path to the 7z.so shared library, but rather the path that _contains_ it. `m_arm64` is not the dynamic library, it just the output folder of the 7z.so library.

This should fix it, provided that the 7z.so file exists:

```cpp
Bit7zLibrary lib{ "/Users/somnambulatory/Downloads/7z2408-src/CPP/7zip/Bundles/Format7zF/b/m_arm64/7z.so" };
```

**Comment by coalooball** [comment]
> Hi!
> 
> > I downloaded source codes of 7zip and run command below to acquire macOS dynamic library `m_arm64`
> 
> ```c++
> Bit7zLibrary lib{ "/Users/somnambulatory/Downloads/7z2408-src/CPP/7zip/Bundles/Format7zF/b/m_arm64" };
> ```
> 
> I think the problem lies here: you're not specifying the correct path to the 7z.so shared library, but rather the path that _contains_ it. `m_arm64` is not the dynamic library, it just the output folder of the 7z.so library.
> 
> This should fix it, provided that the 7z.so file exists:
> 
> ```c++
> Bit7zLibrary lib{ "/Users/somnambulatory/Downloads/7z2408-src/CPP/7zip/Bundles/Format7zF/b/m_arm64/7z.so" };
> ```

I found that `/Users/somnambulatory/Downloads/7z2408-src/CPP/7zip/Bundles/Format7zF/b/m_arm64` is indeed a directory containing `7z.so`.   

After modifying the program according to your code, it runs normally now!   

Thank you very much for your response!

**Comment by rikyoz** [comment]
You're welcome!
