### ISSUE TITLE
[Bug]: Segmentation Fault when call isEncrypted on Android

### ISSUE THREAD

**Issue by uusdnfdsfhnttyh** [rikyoz/bit7z#265]
### bit7z version

4.0.x

### Compilation options

BIT7Z_AUTO_FORMAT

### 7-zip version

v23.01

### 7-zip shared library used

7z.dll / 7z.so

### Compilers

Clang

### Compiler versions

android ndk 27.0.12077973 

### Architecture

arm64

### Operating system

Android

### Operating system versions

Windows 11

### Bug description

I use https://github.com/rikyoz/7-Zip as 7z lib.
I just want to detect whether the archive is encrypted in jni.
```c++
const bit7z::BitArchiveReader reader{lib, "/storage/emulated/0/Download/en.7z", bit7z::BitFormat::SevenZip};
if (reader.isEncrypted()) {
  spdlog::info("{} is encrypted", file_name);
} else {
  spdlog::info("{} is not encrypted", file_name);
}
```
Then a segmentation fault occurred:
![image](https://github.com/user-attachments/assets/a359aeb4-fc89-4593-aca6-0e078c244546)
Please tell me what I did wrong, thank you very much for your help.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
Most of the times, segmentation fault issues happen when using p7zip's `7z.so` without enabling the option `BIT7Z_USE_IUNKNOWN` when configuring and building bit7z.
Though you said that you're using `https://github.com/rikyoz/7-Zip` as 7z lib, so I'm not sure this is your case.
But I would try to enabled the option and test the program, just in case.
Anyway, I'll try to replicate the issue.

**Comment by uusdnfdsfhnttyh** [comment]
You mentioned the BIT7Z_USE_IUNKNOWN compilation option, so I tried to change 
```c++
if( BIT7Z_7ZIP_VERSION VERSION_LESS "23.01" )
  set( BIT7Z_USE_LEGACY_IUNKNOWN ON )
else()
  option( BIT7Z_USE_LEGACY_IUNKNOWN "Enable or disable building using the legacy version of IUnknown" )
endif()
```
 to 
```c++
set( BIT7Z_USE_LEGACY_IUNKNOWN ON ) 
```
in the BuildOptions.cmake file, and segmentation fault disappeared!

Thank you for taking your precious time to reply to me. So far, my question has been solved to some extent.
