### ISSUE TITLE
Custom read/write handlers from user

### ISSUE THREAD

**Issue by kenkit** [rikyoz/bit7z#29]
**Describe the solution you'd like**
Should allow user to set custom read/write handlers e.g when user wants to set http archive reading.

**Additional context (optional)**
This will make the library much more flexible and powerfull.
E.g user can set ftp/http archive url and the library should be able to list/extract without downloading the full archive via custom handlers.

**Comment by kenkit** [comment]
Something like [libarchive](https://github.com/libarchive/libarchive/wiki/Examples) custom read  function example.

**Comment by rikyoz** [comment]
It might be an interesting functionality to support.
Surely it requires several changes, both internally and in the external API, so it will not be released in the next stable version (v3.1).
Perhaps in the next major release (v4.0), but I need to study it more deeply and for now I'm concentrating on other features (like the support to Linux and p7zip).

> E.g user can set ftp/http archive url and the library should be able to list/extract without downloading the full archive via custom handlers.

From v3.1 bit7z supports extraction/metadata reading from `std::istream`.
Are you sure this doesn't fit your use case?

**Comment by kenkit** [comment]
I have not tried it. but I'll look into it.
I appreciate your quick response all the same.

**Comment by kenkit** [comment]
My guess is this feature goes hand in hand with linux compatibility of the library.

**Comment by kenkit** [comment]
Istream will work just fine. Was just doing something with boost iostreams.
