### ISSUE TITLE
Extract 提取的时候，可以不提取文件夹吗

### ISSUE THREAD

**Issue by MrDotH** [rikyoz/bit7z#34]
extractor.extract 提取文件的时候，能把其中的文件夹去掉吗

**Comment by rikyoz** [comment]
Hi.
Sorry but I do not speak Chinese, so I had to use Google Translate, I hope I understood your issue all the same.
If I'm not mistaken, you want to _extract only the files_, not the folders, from an archive.
However, I'm not sure which of the following two cases you are referring to:
+ Extract all the files in an archive, including those inside folders, but _without maintaining the structure of the directories_. Unfortunately, this is not (yet) possible with bit7z, as it _always_ tries to recreate the folder tree as it is in the archive. However, it is a potentially useful functionality, and I hope to implement it in the next version of the library.

Or

+ Extract all files, _ignoring folders and their contents_. 
   In this case, although bit7z does not _directly_ implement this feature, you can achieve the same effect by using [`BitExtractor::extractMatchingRegex(...)`](https://github.com/rikyoz/bit7z/wiki/BitExtractor#void-extractmatchingregex-const-wstring-in_file-const-wstring-regex-const-wstring-out_dir--const) with the Regular Expression `^[^/\\]+$`: such regex matches only archive's files not having `\` or `/` in their path (hence they are not contained in any folder!).

**Comment by rikyoz** [comment]
Implemented in [v4.0.0](https://github.com/rikyoz/bit7z/releases/tag/v4.0.0).
