### ISSUE TITLE
The Callbacks should have a "void*" data in order to pass the "this" pointer in a class usage

### ISSUE THREAD

**Issue by fabri9532** [rikyoz/bit7z#40]
Let me explain:
When I use the library in a class, I need to declare tha Callback procedure as "static" member.
With a static Callback procedure, I need to known from wich class object the call is made.
So I need the "this" pointer to be passed to the Callback.

Modification example:
Set Total callback: setTotalCallback( const TotalCallback &callback, void* lpData )
TotalCallback: void(uint64_t total_size, void* lpData)

**Comment by fabri9532** [comment]
Many thanks for the reply.
The solution you proposed fully meets my needs.

Fabrizio.

**Comment by rikyoz** [comment]
You are welcome, glad to help!

Riccardo
