### ISSUE TITLE
FileCallback should report filename with path

### ISSUE THREAD

**Issue by neolib** [rikyoz/bit7z#46]
I am a new user of this library, hope I am not making fundamental misunderstanding of the lib.

I found that FileCallback only reports bare filename without path information in archive.

Can you make the callback report full path? Full path can be:
- Full path of the extracted file on disk
- Relative path as it appears in archive file

It's up to you to decide which is appropriate.

**Comment by rikyoz** [comment]
Hi, and thank you for using bit7z!

> Can you make the callback report full path? Full path can be:
> 
> * Full path of the extracted file on disk
> * Relative path as it appears in archive file
> 
> It's up to you to decide which is appropriate.

I think it's an excellent idea!
Probably I'll make it report the relative path in the archive.
I was already thinking of changing the FileCallback to provide more information about the current file being processed  (e.g., its size).
I'll evaluate what to do and implement it for the next major release.

I'm currently working on a significant refactoring of the library's internal code, which I don't know how long it will take me (I'm working on it in the spare time).
So I don't have a precise deadline, but I hope to release it as soon as possible.
Thank you again!

**Comment by rikyoz** [comment]
Implemented in [v4.0.0](https://github.com/rikyoz/bit7z/releases/tag/v4.0.0).
