### ISSUE TITLE
Extract rar4.x file fail

### ISSUE THREAD

**Issue by nolanjian** [rikyoz/bit7z#47]
**Describe the bug**
I have try both RAR and RAR5, but fail to extract, it comes out with open file fail, any one can help?

**Comment by nolanjian** [comment]
exception info: Data Error
but my rar4.x file can open in 7zFM and winRAR

**Comment by rikyoz** [comment]
Hi!
This behavior is strange, and I cannot seem to reproduce it with my tests.
For a better understanding of what the problem could be, could you provide me more details?
In particular:

- The 7-zip DLL you are using. Only `7z.dll` supports the extraction of RAR4.x archives. Other DLLs like `7za.dll` support only the 7z format.
- The architecture (x86 or x86_64) and version of the 7-zip DLL. 
- The properties of the RAR4.x archive you're trying to extract (e.g., total size, number of volumes, solid compression, etc.). In this sense, a screenshot of the "Info" window (either of 7-zip FM or WinRAR) would be helpful!
