### ISSUE TITLE
can not find "lib/7zSDK/CPP/Windows/COM.cpp"

### ISSUE THREAD

**Issue by EruditePig** [rikyoz/bit7z#5]
I want to build the staic lib accord to bit7z.pro, but I can not find the "lib/7zSDK/CPP/Windows/COM.cpp" file in 7zip SDK folder. There is a COM.h in "7zSDK/CPP/Windows"  folder. Is this a mistake?

**Comment by rikyoz** [comment]
That file should be there! I've checked also the 7-zip git repository and I can see it (https://github.com/rikyoz/7-Zip/tree/master/CPP/Windows)!

**Comment by EruditePig** [comment]
errrrrr~ I get the 7zip SDK from url "http://www.7-zip.org/a/lzma1604.7z" in its website. You can check that the COM.cpp doesn't exist.

Thank you~

**Comment by rikyoz** [comment]
That's the LZMA SDK. When I'm talking about the "7-zip SDK", I'm referring to the source code of the whole 7-zip project (http://7-zip.org/a/7z1604-src.7z).
