### ISSUE TITLE
Bug]: 

### ISSUE THREAD

**Issue by qinxue123321** [rikyoz/bit7z#51]
### bit7z version

3.1.x

### 7-zip version

v18.05

### 7-zip DLL used

7z.dll

### MSVC version

2017

### Architecture

x86_64

### Which version of Windows are you using?

Windows 10

### Bug description

0x00007FFC797B4ED9 处(位于 7z.exe 中)有未经处理的异常: Microsoft C++ 异常: bit7z::BitException，位于内存位置 0x000000DE7A4FF498 处。 #

### Steps to reproduce

0x00007FFC797B4ED9 处(位于 7z.exe 中)有未经处理的异常: Microsoft C++ 异常: bit7z::BitException，位于内存位置 0x000000DE7A4FF498 处。 

### Expected behavior

  ##0x00007FFC797B4ED9 处(位于 7z.exe 中)有未经处理的异常: Microsoft C++ 异常: bit7z::BitException，位于内存位置 0x000000DE7A4FF498 处。

### Relevant compilation output

```shell
0x00007FFC797B4ED9 处(位于 7z.exe 中)有未经处理的异常: Microsoft C++ 异常: bit7z::BitException，位于内存位置 0x000000DE7A4FF498 处。
```

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi! Sorry, I don't know Chinese, so I used an online translator.
From what I can understand, your code, for some reason, throws a `BitException` (which is a bit7z-specific class for error handling). To better understand the cause, please wrap your code that uses bit7z in a try-catch like the following:

[Automatically translated, sorry for any mistake - 自动翻译，如有错误，敬请原谅]
抱歉，我不懂中文，所以我用了一个在线翻译器。
根据我的理解，你的代码，由于某种原因，抛出了一个 "BitException"（这是一个bit7z专用的错误处理类）。为了更好地了解原因，请将你使用bit7z的代码包在一个try-catch中，如下所示

```cpp
try {
    // Code using bit7z
} catch ( const BitException& ex ) {
    // Use the exception object ex for understanding the problem, e.g.:
    std::cout << ex.what() << std::endl;
}
```
