### ISSUE TITLE
[Feature Request]: mini head-only file for parsing tar packages

### ISSUE THREAD

**Issue by lucasjinreal** [rikyoz/bit7z#52]
### Feature description

I want a mini head-only for **only parsing tar pacakges**.

**BECAUSE I need this functionality on a very edge device which need as small size of program as possible**

### Additional context

I don't need 7z, zip or anything else format, I just want tar packages can be load and read. **not even need write it**

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!
I'm sorry, but I think that **bit7z**, as it is currently implemented, is not a suitable or ideal solution for your use case.
The main problems are:
- **bit7z** is a static library; maybe, there will also be a header-only version of it in the future, but not soon.
- The current version supports only Windows, so it would probably not run on an edge device.
- The next major version (i.e., v4.0) will also support Unix operating systems (e.g., Linux and macOS), but it will always be a simple interface to the `7-zip` (or `p7zip`) shared libraries:
    - **bit7z** doesn't contain the source code for parsing archives: instead, it uses the interfaces provided by `7-zip` for performing the requested operations; the actual code for reading archives is inside the shared library you use along with **bit7z** (e.g., `7z.dll` or `7z.so`).
    - Maybe it is possible to compile a customized shared library of `7-zip` that supports only the `tar` format (I don't know if it is possible, tbh). However, its resource usage might not be suitable for an edge device (as far as I know, 7-zip is mainly designed to run on desktop environments).
