### ISSUE TITLE
Is it possible to remove items from archive?

### ISSUE THREAD

**Issue by vladimir-kraus** [rikyoz/bit7z#55]
### Feature description

The title speaks for itself: is it possible to remove/delete items directly from existing archive?

By "directly" I mean without extracting the archive first to temporary folder on a disk, then removing the items from the disk and compressing it again.

After experimenting with 7z command line tool, it seems to me that 7zip is able to do this. There is a command option for this https://sevenzip.osdn.jp/chm/cmdline/commands/delete.htm and by observing the speed of this operation, it definitely is faster than extracting and compressing back. 

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Implemented in [v4.0.0](https://github.com/rikyoz/bit7z/releases/tag/v4.0.0).
