### ISSUE TITLE
[Bug]: inconsistency in the file Build.txt in v3.1.4 

### ISSUE THREAD

**Issue by fabri9532** [rikyoz/bit7z#56]
### bit7z version

3.1.x

### 7-zip version

v19.00

### 7-zip DLL used

7z.dll

### MSVC version

2017

### Architecture

x86_64

### Which version of Windows are you using?

Windows 10

### Bug description

Is not a real bug.

In the 7z files released of v3.1.4 the "Build.txt" file reports the v3.1.3.
Is the released library the v3.1.4?

Thanks in advance, Fabrizio.

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> Is not a real bug.
> 
> In the 7z files released of v3.1.4 the "Build.txt" file reports the v3.1.3.
> Is the released library the v3.1.4?

Yes, it is the v3.1.4!
Before pushing the new release tag, I forgot to change the version specified in the CI/CD configuration file, which is the value written in the "Build.txt" file. 
But the library version built is the correct one.
I fixed the configuration file just after the release (https://github.com/rikyoz/bit7z/commit/c2db868e70aac4f28c4e792f552968260c141bc8), but I didn't update the released archives. To avoid confusion, I'll probably need to update them, though.
And I'll probably change the AppVeyor configuration to use the tag value as the version in the "Build.txt" file, so I'll not need to change it every time.
Anyway, thanks for pointing it out!

**Comment by fabri9532** [comment]
Thank you for the clarification.

Fabrizio

**Comment by rikyoz** [comment]
I updated the released archives.

> Thank you for the clarification.

You're welcome!
