### ISSUE TITLE
can you post a sample solution in the wiki?

### ISSUE THREAD

**Issue by EruditePig** [rikyoz/bit7z#6]
Hi

I checked the bit7z everyday to see whether you add the callback function. Thank you very much, I am really appreciate your effort.

I try to make a sample solution to test the function and I can compile and link, But when I debug the code ,the line "Bit7zLibrary lib(L"7z.dll");" will abort. I put the 7z.dll in the folder where the exe exist and the dependency walker said nothing dll was missing.

So, can you post a sample solution to teach me how to use the lib? Thank you~

**Comment by rikyoz** [comment]
Hi,
you are welcome! As soon as I can I will provide a complete example in the wiki. Anyway, in the past I had a similar problem when, by mistake, I tried to use a 32 bit 7z.dll with a 64 bit program or viceversa; maybe this is the problem you are encountering! In the future I hope to improve exception messages!

**Comment by EruditePig** [comment]
Hi,
you are right , i download a 32bit 7z.dll, all issue solved.

Thank you!
