### ISSUE TITLE
[Feature Request]: How to us Multi-volume archives

### ISSUE THREAD

**Issue by fengshaoxie** [rikyoz/bit7z#62]
### Feature description

can write an example to use Multi-volume archives

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

Here are some examples:

### Extraction

For all multi-volume archive types, except RAR ones:
```cpp
BitExtractor extractor{lib, BitFormat::Split};
extractor.extract(L"archive.7z.001", L"./out_dir/");
```

RAR and RAR5 archives use a different multi-volume scheme:
```cpp
BitExtractor extractor{lib, BitFormat::Rar5};
extractor.extract(L"archive.part1.rar", L"./out_dir/");
```

```cpp
BitExtractor extractor{lib, BitFormat::Rar};
extractor.extract(L"archive.rar", L"./out_dir/");
```

### Creation

```cpp
BitCompressor compressor{lib, BitFormat::SevenZip};
compressor.setVolumeSize(42 * 1024 * 1024); // size (in bytes) of the volumes; in this case, 42MB
compressor.compressDirectory(L"in_dir/", L"archive.7z");
```

Notes: 
   - you need to specify the volume size for creating multi-volume archives;
   - the output archive volume files will all have the "archive.7z" prefix, and will have incremental numbers as extensions, e.g., "archive.7z.001", "archive.7z.002", etc...
