### ISSUE TITLE
[Feature Request]: Get extract result

### ISSUE THREAD

**Issue by chifandeyu** [rikyoz/bit7z#85]
### Feature description

Can get extract result when extract finish?

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi! Could you be more specific? What do you mean by "extract result"?

**Comment by chifandeyu** [comment]
Sorry, I didn't describe it clearly.  I want to listen to the total progress when extracting archive file. And whether the decompression is successful.

**Comment by rikyoz** [comment]
> Sorry, I didn't describe it clearly.

No problem!

> I want to listen to the total progress when extracting archive file.

You have to set both the total size and the progress size callbacks. You can use the setter functions [`BitExtractor::setTotalCallback`](https://github.com/rikyoz/bit7z/wiki/BitExtractor#void-settotalcallback-const-totalcallback-callback-) and [`BitExtractor::setProgressCallback`](https://github.com/rikyoz/bit7z/wiki/BitExtractor#void-setprogresscallback-const-progresscallback-callback-).
E.g.:
```cpp
//...
uint64_t total = 0; // We need a global total variable in order to calculate the progress percentage
extractor.setTotalCallback([this, &total](uint64_t total_size) {
    total_size = total; // It will be called only once at the start of the extraction process.
});
extractor.setProgressCallback([this, &total](uint64_t progress_size) {
    std::cout << "Extracting... " 
              << static_cast<int>( ( 100.0 * progress_size ) / total ) << "%" << std::endl;
});
//...
```

> And whether the decompression is successful.

If the extraction function of `BitExtractor` finishes without throwing exceptions, it means that the decompression was successful. Otherwise, the function will throw a `BitException` object.

**Comment by chifandeyu** [comment]
> > Sorry, I didn't describe it clearly.
> 
> No problem!
> 
> > I want to listen to the total progress when extracting archive file.
> 
> You have to set both the total size and the progress size callbacks. You can use the setter functions [`BitExtractor::setTotalCallback`](https://github.com/rikyoz/bit7z/wiki/BitExtractor#void-settotalcallback-const-totalcallback-callback-) and [`BitExtractor::setProgressCallback`](https://github.com/rikyoz/bit7z/wiki/BitExtractor#void-setprogresscallback-const-progresscallback-callback-).
> E.g.:
> ```cpp
> //...
> uint64_t total = 0; // We need a global total variable in order to calculate the progress percentage
> extractor.setTotalCallback([this, &total](uint64_t total_size) {
>     total_size = total; // It will be called only once at the start of the extraction process.
> });
> extractor.setProgressCallback([this, &total](uint64_t progress_size) {
>     std::cout << "Extracting... " 
>               << static_cast<int>( ( 100.0 * progress_size ) / total ) << "%" << std::endl;
> });
> //...
> ```
> 
> > And whether the decompression is successful.
> 
> If the extraction function of `BitExtractor` finishes without throwing exceptions, it means that the decompression was successful. Otherwise, the function will throw a `BitException` object.

👍That's great! Thx.
