### ISSUE TITLE
[Bug]: bit7z.pro compilation fails

### ISSUE THREAD

**Issue by neomissing** [rikyoz/bit7z#88]
### bit7z version

3.1.x

### 7-zip version

v21.07

### 7-zip DLL used

7z.dll

### MSVC version

mingw

### Architecture

x86

### Bug description

bit7z.pro compilation fails

### Code of Conduct

- [X] By submitting this issue, I agree to follow bit7z's [Code of Conduct](https://github.com/rikyoz/bit7z/blob/master/CODE_OF_CONDUCT.md)

**Comment by rikyoz** [comment]
Hi!

> MSVC version
> mingw

Unfortunately, bit7z v3.1.x doesn't support MinGW compilers. 
Support to MinGW will be added to the next major version v4.
